version: '3.8'

services:
  db_auth:
    image: postgres:15
    container_name: db_auth
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - dados_postgres_auth:/var/lib/postgresql/data
    networks:
      - orquestrador-net
    # Healthcheck para garantir que o banco est√° pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: .
    container_name: auth_service_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db_auth:
        condition: service_healthy
    networks:
      - orquestrador-net

volumes:
  dados_postgres_auth:

networks:
  orquestrador-net:
    external: true